services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client

  client:
    build: ./client
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - analysis
      - auth
      - history
      - upload

  analysis:
    tty: true
    build: ./services/analysis
    command: python3 ./app/main.py
    depends_on:
      - auth

  auth:
    tty: true
    build: ./services/auth
    env_file: ./services/auth/.env
    command: python3 ./app/main.py
    depends_on:
      - history

  history:
    tty: true
    build: ./services/history
    command: python3 ./app/main.py
    depends_on:
      - upload

  upload:
    tty: true
    build: ./services/upload
    command: python3 ./app/main.py
    