version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client

  client:
    build: ./client
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - analysis
      - auth
      - history
      - upload

  analysis:
    build: ./services/analysis
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  auth:
    build: ./services/auth
    env_file: ./services/auth/.env
    ports:
      - "8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001

  history:
    build: ./services/history
    ports:
      - "8002:8002"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002

  upload:
    build: ./services/upload
    ports:
      - "8003:8003"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003
    