services:
  analysis:
    build: ./services/analysis
    restart: always
    ports:
      - "8001:8000"
    networks:
      - app-network
    
  auth:
    build: ./services/auth
    restart: always
    ports:
      - "8002:8000"
    networks:
      - app-network

  history:
    build: ./services/history
    restart: always
    ports:
      - "8003:8000"
    networks:
      - app-network

  upload:
    build: ./services/upload
    restart: always
    ports:
      - "8004:8000"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - analysis
      - auth
      - history
      - upload

  frontend:
    build: ./client
    # ports:
    #   - '3000:80'
    # environment:
    #   - VITE_HOST=0.0.0.0
    volumes:
      - frontend-dist:/app/dist
    networks:
      - app-network
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge

volumes:
  frontend-dist:
  