services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
    logging:
      driver: none

  client:
    build: ./client
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - analysis
      - auth

  analysis:
    tty: true
    build: ./services/analysis
    command: python3 ./app/main.py
    ports: 
      - 8000:8000
    depends_on:
      - auth

  auth:
    tty: true
    build: ./services/auth
    env_file: ./services/auth/.env
    command: python3 ./app/main.py

    